2018-01-04 09:54:03 TRACE - transferfund() invoked in service
2018-01-04 09:54:03 TRACE - gwt account method invoked
2018-01-04 09:54:03 DEBUG - checking the aid against the map key
2018-01-04 09:54:03 ERROR - no id found
com.sapient.exceptions.IdException: no id found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:31)
	at com.sapient.service.SerImpl.transferFund(SerImpl.java:35)
	at com.sapient.client.TransferClient.main(TransferClient.java:45)
